apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarqube
  name: sonarqube-sonarqube-nodeport
  namespace: sonarqube
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: http
    nodePort: 30009
  selector:
    app: sonarqube
    release: sonarqube
  type: NodePort
